/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pi;

import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Toolkit;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import koneksi.koneks;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author abi
 */
public class Menu_Utama extends javax.swing.JFrame {
    Connection conn =null;
    java.sql.Statement st = null;
    int xmouse;
    int ymouse; 
    /**
     * Creates new form Menu_Utama
     */
    public Menu_Utama() {
        initComponents();
        datatable();
        setBackground(new Color(0,0,0,0));
        setIcon();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode Pemilik");
        tbl.addColumn("Nama Pemilik");
        tbl.addColumn("Kelas Pelayanan");
        tbl.addColumn("Nama Hewan");
        tbl.addColumn("Jenis Hewan");
        tbl.addColumn("Status Hewan");
        tbl.addColumn("Alamat");
        jTable1.setModel(tbl);
        try{
            Statement statement = (Statement) koneks.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from petshop");
            while (res.next())
            {
                tbl.addRow(new Object []{
                        res.getString("Kode_Pemilik"),
                        res.getString("Nama_Pemilik"),
                        res.getString("Kelas_Pelayanan"),
                        res.getString("Nama_Hewan"),
                        res.getString("Jenis_Hewan"),
                        res.getString("Status_Hewan"),
                        res.getString("Alamat"),
                });
                jTable1.setModel(tbl);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(100, 800));
        setSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(null);

        jLabel2.setText("Nama Pemilik");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 350, 80, 30);

        jLabel3.setText("Kode Pemilik");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 300, 80, 30);

        jLabel6.setText("Nama Hewan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 400, 80, 30);

        jLabel7.setText("Status Hewan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 450, 80, 30);

        jLabel8.setText("Alamat");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 400, 50, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pi/images/close_1.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(950, 10, 40, 40);

        jLabel10.setText("Kelas Pelayanan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(360, 300, 100, 30);

        jLabel11.setText("Jenis Hewan");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(360, 350, 100, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 300, 160, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 350, 160, 30);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(150, 400, 160, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(150, 450, 160, 30);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(710, 480, 160, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "VIP" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(470, 300, 100, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anjing", "Burung", "Kelinci", "Kucing" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(470, 350, 100, 30);

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(710, 290, 80, 23);

        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(710, 330, 80, 23);

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(710, 370, 80, 23);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(710, 410, 80, 23);

        jButton5.setText("Cari");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(890, 480, 63, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 390, 240, 100);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 510, 620, 190);

        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel12MouseDragged(evt);
            }
        });
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1000, 720);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pi/images/fx.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 800));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 770);

        setSize(new java.awt.Dimension(999, 716));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("images/closeho.png"));
        jLabel9.setIcon(A);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        ImageIcon B = new ImageIcon(getClass().getResource("images/close_1.png"));
        jLabel9.setIcon(B);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        ImageIcon A = new ImageIcon(getClass().getResource("images/closec.png"));
        jLabel9.setIcon(A);
    }//GEN-LAST:event_jLabel9MousePressed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jLabel12MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xmouse, y - ymouse);
        System.out.println(x+","+y);
    }//GEN-LAST:event_jLabel12MouseDragged

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_jLabel12MousePressed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jTextField2.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextArea1.setText("");
        jComboBox1.setSelectedItem(this);
        jComboBox2.setSelectedItem(this);
        jTextField1.requestFocus();
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                       
        String Kode_Pemilik = jTextField1.getText();
        String Nama_Pemilik = jTextField2.getText();
        String Kelas_Pelayanan = (String) jComboBox1.getSelectedItem();
        String Nama_Hewan = jTextField5.getText();
        String Jenis_Hewan = (String) jComboBox2.getSelectedItem();
        String Status_Hewan = jTextField6.getText();
        String Alamat = jTextArea1.getText();

    try{
        Statement statement = (Statement) koneks.getConnection().createStatement();
        statement.executeUpdate("insert into petshop VALUES ('" + Kode_Pemilik + "','" + Nama_Pemilik +"','"+ Kelas_Pelayanan +"','"+Nama_Hewan +"','"+Jenis_Hewan +"','"+Status_Hewan +"','"+ Alamat +"');");
        statement.close();
        JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
    }catch (Exception t){
        JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
    }
    datatable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jButton3.getText() == "jButton3"){
           jTextField1.requestFocus();
        }else{
            String Kode_Pemilik = jTextField1.getText();
            String Nama_Pemilik = jTextField2.getText();
            String Kelas_Pelayanan = (String) jComboBox1.getSelectedItem();
            String Nama_Hewan = jTextField5.getText();
            String Jenis_Hewan = (String) jComboBox2.getSelectedItem();
            String Status_Hewan = jTextField6.getText();
            String Alamat = jTextArea1.getText();
            
        try{
            Statement statement = (Statement) koneks.getConnection().createStatement();
            statement.executeUpdate ("update petshop SET Kode_Pemilik='"+Kode_Pemilik+"',"+"Nama_Pemilik='"+Nama_Pemilik+"',"+"Kelas_Pelayanan='"+Kelas_Pelayanan+"',"+"Nama_Hewan='"+Nama_Hewan+"',"+"Jenis_Hewan='"+Jenis_Hewan+"',"+"Status_Hewan='"+Status_Hewan+"',"+"Alamat='"+Alamat+"'" + "WHERE Kode_Pemilik = '"+Kode_Pemilik+"' OR Nama_Pemilik = '"+Nama_Pemilik+"'"); 
            statement.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
        }catch (Exception t){
            JOptionPane.showMessageDialog(null, "Data Gagal diubah");
        }
        datatable();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String Kode_Pemilik = jTextField1.getText();
        String Nama_Pemilik = jTextField2.getText();
        try{
            Statement statement = (Statement) koneks.getConnection().createStatement();
            statement.executeUpdate("delete from petshop where Kode_Pemilik = '" +Kode_Pemilik+"'OR Nama_Pemilik ='"+Nama_Pemilik+"';");
            JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
            jTextField2.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextArea1.setText("");
            jComboBox1.setSelectedItem(this);
            jComboBox2.setSelectedItem(this);
            jTextField1.requestFocus();
        }catch (Exception t){
            JOptionPane.showMessageDialog(null, "Data Gagal di Hapus");
        }
        datatable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            Statement statement = (Statement) koneks.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select*from petshop where "+" Kode_Pemilik like'%" + jTextField7.getText() + "%' OR "+" Nama_Pemilik like'%" + jTextField7.getText() + "%'");
            DefaultTableModel tbl = new DefaultTableModel();
                tbl.addColumn("Kode Pemilik");
                tbl.addColumn("Nama Pemilik");
                tbl.addColumn("Kelas Pelayanan");
                tbl.addColumn("Nama Hewan");
                tbl.addColumn("Jenis Hewan");
                tbl.addColumn("Status Hewan");
                tbl.addColumn("Alamat");
                
                jTable1.setModel(tbl);
                while (res.next()){
                    tbl.addRow(new Object[]{
                        res.getString("Kode_Pemilik"),
                        res.getString("Nama_Pemilik"),
                        res.getString("Kelas_Pelayanan"),
                        res.getString("Nama_Hewan"),
                        res.getString("Jenis_Hewan"),
                        res.getString("Status_Hewan"),
                        res.getString("Alamat"),
                    });
                    jTable1.setModel(tbl);
                }
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    
                  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/ico.png")));
    }
}
